import { Cairo } from "next/font/google";
import "./globals.css";
import AuthContext from "@/contexts/AuthContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
import UniverstyContext from "@/contexts/UniverstyContext";

const cairo = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body dir="rtl" className={`${cairo.className}`}>
        <GoogleOAuthProvider clientId="163765837453-36u3q907atavukoaee16anrigd2bt7re.apps.googleusercontent.com">
          <AuthContext>
            <UniverstyContext>{children}</UniverstyContext>
          </AuthContext>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
